package workingArea;

import java.util.Scanner;

/**
 * Created by
 * Filmon Ghirmai (skynet) on 9/2/17.
 * Software Developer
 */
public class TestProgram {
    public static void main(String[] args) {
        Scanner in = new Scanner(System.in);
        String str1 = "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO" ;
        String str2 = "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO";

        System.out.println(str1.length());
        System.out.println(str2.length());
        System.out.println(str1.length() - str2.length());

        System.out.println(str1.equals(str2));

    }
}
